[package]
name                   = "quack-cli"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
publish                = false

[lints]
workspace = true

[dependencies]
quack-core = { path = "../quack-core" }
anyhow     = { workspace = true, features = ["std"] }
clap       = { workspace = true, features = ["derive", "error-context", "help", "std", "usage"] }
serde      = { workspace = true, features = ["derive", "std"] }
serde_json = { workspace = true, features = ["std"] }
tokio      = { workspace = true, features = ["rt-multi-thread", "macros", "sync", "signal", "net", "time", "fs"] }
tracing    = { workspace = true, features = ["std"] }

[dev-dependencies]
quack-testkit = { path = "../quack-testkit" }
jiff          = { workspace = true, features = ["serde", "std"] }
tempfile      = { workspace = true }
