[package]
name                   = "quack"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
publish                = false

[[bin]]
name = "quack"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
quack-core         = { path = "../quack-core" }
anyhow             = { workspace = true, features = ["std"] }
askama             = { workspace = true, features = ["derive", "std", "config"] }
axum               = { workspace = true, features = ["http1", "json", "query", "form", "tokio", "multipart", "matched-path"] }
axum-extra         = { workspace = true, features = ["cookie", "form"] }
base64             = { workspace = true, features = ["std"] }
clap               = { workspace = true, features = ["derive", "error-context", "help", "std", "usage"] }
crossterm          = { workspace = true, features = ["events", "event-stream"] }
dirs               = { workspace = true }
futures            = { workspace = true, features = ["std"] }
jiff               = { workspace = true, features = ["std"] }
mimalloc           = { workspace = true, features = ["secure"] }
mime_guess         = { workspace = true }
pulldown-cmark     = { workspace = true, features = ["html"] }
ratatui            = { workspace = true, features = ["crossterm"] }
rmcp               = { workspace = true, features = ["server", "macros", "transport-io", "transport-streamable-http-server"] }
ratatui-textarea   = { workspace = true, features = ["crossterm"] }
rust-embed         = { workspace = true, features = ["deterministic-timestamps"] }
serde              = { workspace = true, features = ["derive", "std"] }
schemars           = { workspace = true, features = ["derive"] }
serde_json         = { workspace = true, features = ["std"] }
shlex              = { workspace = true, features = ["std"] }
tempfile           = { workspace = true }
tokio              = { workspace = true, features = ["rt-multi-thread", "macros", "sync", "signal", "net", "time"] }
tokio-util         = { workspace = true }
tower              = { workspace = true, features = ["util"] }
tower-http         = { workspace = true, features = ["timeout", "request-id", "limit", "trace"] }
tower_governor     = { workspace = true, features = ["axum"] }
tracing            = { workspace = true, features = ["std"] }
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter", "std"] }
uuid               = { workspace = true, features = ["std", "v7"] }

[dev-dependencies]
sqlx = { workspace = true, features = ["runtime-tokio", "sqlite"] }
